import { a as day1a } from './day1/a.js';
import { b as day1b } from './day1/b.js';
import { a as day2a } from './day2/a.js';
import { b as day2b } from './day2/b.js';
import { a as day3a } from './day3/a.js';
import { b as day3b } from './day3/b.js';
import { a as day4a } from './day4/a.js';
import { b as day4b } from './day4/b.js';
import { a as day5a } from './day5/a.js';
import { b as day5b } from './day5/b.js';
import { a as day6a } from './day6/a.js';
import { b as day6b } from './day6/b.js';
import { a as day7a } from './day7/a.js';
import { b as day7b } from './day7/b.js';
import { a as day8a } from './day8/a.js';
import { b as day8b } from './day8/b.js';

console.log(`Day 1: ${day1a}, ${day1b}`);
console.log(`Day 2: ${day2a}, ${day2b}`);
console.log(`Day 3: ${day3a}, ${day3b}`);
console.log(`Day 4: ${day4a}, ${day4b}`);
console.log(`Day 5: ${day5a}, ${day5b}`);
console.log(`Day 6: ${day6a}, ${day6b}`);
console.log(`Day 7: ${day7a}, ${day7b}`);
console.log(`Day 8: ${day8a}, ${day8b}`);
